Repository fga-eps-mds/2022.2-Amis-Doc, pull requests merged in 2022-12, with the labels that each got.

#42 #41 Erro de digitação
  docs/Guia_Contribuicao/guia_contribuicao.md
Labels: bug, EASY, MDS

#48 #28 arquitetura
  docs/Arquitetura/arquitetura.md
  docs/assets/arquitetura.jpeg
  docs/assets/conceitual.jpeg
  docs/assets/logico.jpeg
  docs/assets/logo_azure.png
  docs/assets/logo_docker.png
  docs/assets/logo_fast_api.png
  docs/assets/logo_my_sql.png
  docs/assets/logo_react_js.png
  docs/assets/logo_visx.png
  docs/assets/report_lab.svg
  docs/assets/useCase.jpeg
Labels: documentation

#44 #33 eap
  docs/Planejamento/EAP/eap.md
  docs/assets/eap.png
  mkdocs.yml
Labels: documentation

#79 31 Prototipo
  docs/Visual/prototipo_alta.md
  docs/assets/PrototipoAlta_alunaCadastro.jpg
  docs/assets/PrototipoAlta_login.jpg
  docs/assets/PrototipoAlta_receita_(1).jpg
  docs/assets/PrototipoAlta_relatorio.jpg
  docs/assets/PrototipoAlta_turmas.jpg
Labels: EPS, DOCS, MDS
